version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
  commands:
#   Following documentation at https://docs.readthedocs.io/en/latest/build-customization.html#install-dependencies-with-uv
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --extra docs --frozen
    - uv run -m sphinx -T -b html -d docs/build/source -D language=en docs $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
  
formats:
  - pdf
